// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCOVk1JXl5C-HrwGBzks8rT5rS8O56Q90',
    appId: '1:1007019774379:web:61589e3874ba7695e082ee',
    messagingSenderId: '1007019774379',
    projectId: 'slips-warranty-tracker',
    authDomain: 'slips-warranty-tracker.firebaseapp.com',
    storageBucket: 'slips-warranty-tracker.firebasestorage.app',
    measurementId: 'G-C2RF7ZMKRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfjDZ6ES3WEp8gt9PvzIOkIwrKTT_iXLU',
    appId: '1:1007019774379:android:8f2399d800da5d08e082ee',
    messagingSenderId: '1007019774379',
    projectId: 'slips-warranty-tracker',
    storageBucket: 'slips-warranty-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeulIeMasMWs7AwqYCYHbk2m_voCYpTn8',
    appId: '1:1007019774379:ios:584a079e835536dfe082ee',
    messagingSenderId: '1007019774379',
    projectId: 'slips-warranty-tracker',
    storageBucket: 'slips-warranty-tracker.firebasestorage.app',
    iosBundleId: 'com.slips.warrantytracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeulIeMasMWs7AwqYCYHbk2m_voCYpTn8',
    appId: '1:1007019774379:ios:584a079e835536dfe082ee',
    messagingSenderId: '1007019774379',
    projectId: 'slips-warranty-tracker',
    storageBucket: 'slips-warranty-tracker.firebasestorage.app',
    iosBundleId: 'com.slips.warrantytracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCOVk1JXl5C-HrwGBzks8rT5rS8O56Q90',
    appId: '1:1007019774379:web:ab5d23f2d1c800d3e082ee',
    messagingSenderId: '1007019774379',
    projectId: 'slips-warranty-tracker',
    authDomain: 'slips-warranty-tracker.firebaseapp.com',
    storageBucket: 'slips-warranty-tracker.firebasestorage.app',
    measurementId: 'G-MG3K8FXFMV',
  );
}
